baseurl = "https://www.fabriciocc.com"
title = "Andres Cordova"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Hiyperion"

[params]
  author = "Andrés Córdova"
  info = "Backend Developer and Data Scientist"
  description = "Andres Cordova's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://i.imgur.com/qZVGgqO.png"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  [taxonomies]
  category = "categories"
  series = "series"

  author = "authors"

  # Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Hiyperion/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-researchgate fa-2x"
  weight = 3
  url = "https://www.researchgate.net/profile/Andres-Cordova-10"

[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/fabriciocordova/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url  = "about/aboutandres/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"
[[menu.main]]
  name = "Contact me"
  weight = 4
  url = "/contacto/"
